### ISSUE TITLE
Cake.Wyam "Could not execute because the specified command or file was not found" error

### ISSUE THREAD

**Issue by savornicesei** [Wyam2/wyam#25]
**Steps to reproduce**
1. clone Wyam2 docs repo to a folder that has space in its name
2. build docs

It will fail with this:
```
========================================
Generate-Themes
========================================
Executing task: Generate-Themes
Cleaning directory D:/Simona Avornicesei/Projects/Wyam2/docs/scaffold
Executing: "dotnet" D:/Simona Avornicesei/Projects/Wyam2/docs/tools/Wyam.2.2.9/tools/netcoreapp2.1/Wyam.dll new --recipe "blog" "D:/Simona Avornicesei/Projects/Wyam2/docs/scaffold"
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet-D:/Simona does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
An error occurred when executing task 'Generate-Themes'.
Error: System.AggregateException: One or more errors occurred. (Wyam: Process returned an error (exit code 1).) ---> Cake.Core.CakeException: Wyam: Process returned an error (exit code 1).
   at Cake.Core.Tooling.Tool`1.ProcessExitCode(Int32 exitCode) in C:\projects\cake\src\Cake.Core\Tooling\Tool.cs:line 139
   at Cake.Core.Tooling.Tool`1.Run(TSettings settings, ProcessArgumentBuilder arguments, ProcessSettings processSettings, Action`1 postAction) in C:\projects\cake\src\Cake.Core\Tooling\Tool.cs:line 119
   at Cake.Wyam.WyamRunner.Run(WyamSettings settings)
   at Submission#0.Wyam(WyamSettings settings)
   at Submission#0.<<Initialize>>b__0_2()
   at Cake.Core.CakeTaskBuilderExtensions.<>c__DisplayClass20_0.<Does>b__0(ICakeContext x) in C:\projects\cake\src\Cake.Core\CakeTaskBuilder.Execution.cs:line 82
   at Cake.Core.CakeTask.<Execute>d__43.MoveNext() in C:\projects\cake\src\Cake.Core\CakeTask.cs:line 125
```

[AB#7](https://dev.azure.com/Wyam2/2bd6d821-49c5-4fc9-9059-7e0d3ac65049/_workitems/edit/7)

**Comment by savornicesei** [comment]
Trigger sync issue to AZDO-B
